### PR TITLE
Add crabsort plugin

### PR DESCRIPTION
**Pull request by alec-hoyland**
* Fix bug with finding the containing folder of the script's path
* Fix bug where data aren't saved in version 7.3 of .mat files
* Save paths as variables for speed and readability
* Add crabsort plugin using decentralized format

### CODE REVIEW

**Comment by alec-hoyland** [comment]
- [x] Shows up on `plugins` list?
- [x] Clusters sample data?
- [x] Shows up in `crabsort` dropdown menu?
- [x] Clusters in `crabsort`?

**Comment by sg-s** [comment]
ready to merge?

**Comment by alec-hoyland** [comment]
I don't have any nice data lying around to test it. If you can cluster with it, or want to pass me data I'll test it further.

**Comment by sg-s** [comment]
Look at the ABF files here:

https://github.com/marderlab/Burst-detection-challenge

**Comment by alec-hoyland** [comment]
UMAP works in crabsort. It shows up on the plugins list, in the dropdown menu, and clusters correctly, saving the results in the object.

**Comment by alec-hoyland** [comment]
fixed
> There seems to be a problem with the clustering visualization that is nonspecific to which dimensionality-reduction algorithm is used (https://github.com/sg-s/crabsort/issues/242), so perhaps it is best to hold off merging until that is resolved.

**Comment by alec-hoyland** [comment]
UMAP works in crabsort. Do you have any thoughts on how plugin options should be exposed to the user? Currently, the plugin uses the options file saved in the `umap-matlab-wrapper` directory, which is probably fine, since the user can change that for their specific application if they need to, though it might be nice to expose the `umap` object to the user. Currently, it's instantiated on-the-fly when dimensionality-reduction is performed.

**Comment by sg-s** [comment]
I hope the changes you've made to the python script are good, merging!

**Pull request merged**
